---
- name: Update RPi hostname
  hostname:
    name: "{{ raspi_config_hostname }}"

- name: Manage /etc/hosts entries applying J2 template
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: "0644"

- name: Configure static IPv4 addressing
  template:
    src: dhcpcd.conf.j2
    dest: /etc/dhcpcd.conf
    owner: root
    group: netdev
    mode: "0664"
  notify: restart networking
