---
- name: Manage /etc/wpa_supplicant/wpa_supplicant.conf configuration applying J2 template
  template:
    src: wpa_supplicant.conf.j2
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    owner: root
    group: root
    mode: '0600'